CustomTagHelper/CustomTagHelper/Models/CustomerViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace CustomTagHelper.Models
{
    public class CustomerViewModel
    {
        public int Id { get; set; }
        //[MaxLength(20)]
        public string? Firstname {  get; set; }
        //[MaxLength(20)]
        public string? Lastname { get; set; }
        //[Required]
        //[StringLength(12)]
        public string Username { get; set; }
        public DateTime? BirthDate { get; set; }
        //[MaxLength(20)]
        public string Email { get; set; }
    }
}

CustomTagHelper/CustomTagHelper/Models/ErrorViewModel.cs
namespace CustomTagHelper.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CustomTagHelper/CustomTagHelper/Controllers/CustomerController.cs
using CustomTagHelper.Models;
using FluentValidation;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Globalization;

namespace CustomTagHelper.Controllers
{
    public class CustomerController : Controller
    {
        #region private property
        private readonly string _sessionKey = "customers";
        private readonly IValidator<CustomerViewModel> _validator;
        #endregion
        #region public property
        public List<CustomerViewModel> Customers 
        { 
            get
            {
                if(string.IsNullOrEmpty(HttpContext.Session.GetString(_sessionKey)) )
                {
                    var list = new List<CustomerViewModel>()
                    {
                        new CustomerViewModel()
                        {
                            Id = 1,
                            Firstname = "Eric",
                            Lastname = "Johnson",
                            Username = "Eric.J",
                            BirthDate = DateTime.ParseExact("01/01/1970", "dd/MM/yyyy", CultureInfo.InvariantCulture),
                            Email = "eric.johnson@test.com"
                        },
                        new CustomerViewModel()
                        {
                            Id = 2,
                            Firstname = "Carlos",
                            Lastname = "Santana",
                            Username = "Carlos.S",
                            BirthDate = DateTime.ParseExact("02/02/1971", "dd/MM/yyyy", CultureInfo.InvariantCulture),
                            Email = "carlos.santana@test.com"
                        }
                    };
                    HttpContext.Session.SetString(_sessionKey, JsonConvert.SerializeObject(list));
                }
                return JsonConvert.DeserializeObject<List<CustomerViewModel>>(HttpContext.Session.GetString(_sessionKey));
            }

            set
            {
                if(value == null)
                {
                    HttpContext.Session.SetString(_sessionKey, JsonConvert.SerializeObject(new List<CustomerViewModel>()));
                }
                else
                {
                    HttpContext.Session.SetString(_sessionKey, JsonConvert.SerializeObject(value));
                }
                
            }
        }
        #endregion

        public CustomerController(IValidator<CustomerViewModel> val) 
        { 
            _validator = val;
        }

        // GET: CustomerController
        public ActionResult Index()
        {
            return View(Customers);
        }

        // GET: CustomerController/Details/5
        public ActionResult Details(int id)
        {
            var model = Customers.Where(x => x.Id == id).FirstOrDefault();
            return View(model);
        }

        // GET: CustomerController/Create
        public ActionResult Create()
        {
            var nextId = Customers.Select(x => x.Id).Max() + 1;
            return View(new CustomerViewModel() { Id = nextId });
        }

        // GET: CustomerController/Create
        public ActionResult AjaxCreate()
        {
            return View();
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CustomerViewModel model)
        {
            if (ModelState.IsValid)
            {

            }
            try
            {
                //var result = await _validator.ValidateAsync(model);
                //if (!result.IsValid)
                //{
                //    result.AddToModelState(this.ModelState);
                //    return View("Create", model);
                //}

                var list = Customers;
                list.Add(model);
                Customers = list;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                // to log:
                throw new Exception("Server error!");
            }
        }

        // POST: CustomerController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AjaxCreate(CustomerViewModel model)
        {
            try
            {
                var result = await _validator.ValidateAsync(model);
                if (!result.IsValid)
                {
                    result.AddToModelState(this.ModelState);
                    return View("Create", model);
                }

                var list = Customers;
                list.Add(model);
                Customers = list;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                // to log:
                throw new Exception("Server error!");
            }
        }

        // GET: CustomerController/Edit/5
        public ActionResult Edit(int id)
        {
            var model = Customers.Where(x => x.Id == id).FirstOrDefault();
            return View(model);
        }

        // POST: CustomerController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CustomerViewModel model)
        {
            try
            {
                //var model = Customers.FirstOrDefault(x => x.Id == id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: CustomerController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: CustomerController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CustomTagHelper/CustomTagHelper/Controllers/HomeController.cs
using CustomTagHelper.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CustomTagHelper.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CustomTagHelper/CustomTagHelper/Views/Customer/AjaxCreate.cshtml
@{
    ViewData["Title"] = "Create";
}

<h1>AJAX Create</h1>

<h4>CustomerViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @await Html.PartialAsync("_AjaxCreatePartialView.cshtml")
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CustomTagHelper/CustomTagHelper/Views/Customer/Create.cshtml
@model CustomTagHelper.Models.CustomerViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>CustomerViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @await Html.PartialAsync("_CreatePartialView.cshtml", Model)
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CustomTagHelper/CustomTagHelper/Views/Customer/Details.cshtml
@model CustomTagHelper.Models.CustomerViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>partial view</h4>

    <hr />
    @await Html.PartialAsync("_DetailsPartialView.cshtml", Model)

    <h4>custom tag</h4>
    <hr />
    <customer-info value="Model"></customer-info>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id}) |
    <a asp-action="Index">Back to List</a>
</div>

CustomTagHelper/CustomTagHelper/Views/Customer/Edit.cshtml
@model CustomTagHelper.Models.CustomerViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CustomerViewModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        @await Html.PartialAsync("_EditPartialView.cshtml", Model)
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CustomTagHelper/CustomTagHelper/Views/Customer/Index.cshtml
@model IEnumerable<CustomTagHelper.Models.CustomerViewModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<p>
    <a asp-action="Create">AJAX Create New</a>
</p>

@await Html.PartialAsync("_IndexPartialView.cshtml", Model)

CustomTagHelper/CustomTagHelper/Views/Customer/_AjaxCreatePartialView.cshtml
<div id="divCustomerForm">
    <div class="text-danger"></div>
    <div class="form-group">
        <label for="Id" class="control-label"></label>
        <input name="Id" class="form-control" />
        <div class="invalid-feedback"></div>
    </div>
    <div class="form-group">
        <label for="Firstname" class="control-label"></label>
        <input name="Firstname" class="form-control" />
        <div class="invalid-feedback"></div>
    </div>
    <div class="form-group">
        <label for="Lastname" class="control-label"></label>
        <input name="Lastname" class="form-control" />
        <div class="invalid-feedback"></div>
    </div>
    <div class="form-group">
        <label for="Username" class="control-label"></label>
        <input for="Username" class="form-control" />
        <div class="invalid-feedback"></div>
    </div>
    <div class="form-group">
        <label for="BirthDate" class="control-label"></label>
        <input name="BirthDate" class="form-control" />
        <div class="invalid-feedback"></div>
    </div>
    <div class="form-group">
        <label for="Email" class="control-label"></label>
        <input name="Email" class="form-control" />
        <div class="invalid-feedback"></div>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
        <ajax-button ajax-controller="customer" ajax-action="ajaxcreate" ajax-method="post" 
            ajax-target-id="divCustomerForm" ajax-call-success="validateCustomerInput" ajax-call-failure="">Submit</ajax-button>
    </div>
</div>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

CustomTagHelper/CustomTagHelper/Views/Customer/_CreatePartialView.cshtml
@model CustomTagHelper.Models.CustomerViewModel

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Id" class="control-label"></label>
        <input asp-for="Id" class="form-control" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Firstname" class="control-label"></label>
        <input asp-for="Firstname" class="form-control" />
        <span asp-validation-for="Firstname" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Lastname" class="control-label"></label>
        <input asp-for="Lastname" class="form-control" />
        <span asp-validation-for="Lastname" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Username" class="control-label"></label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BirthDate" class="control-label"></label>
        <input asp-for="BirthDate" class="form-control" />
        <span asp-validation-for="BirthDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Create" class="btn btn-primary" />
    </div>
</form>

@*@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
*@

CustomTagHelper/CustomTagHelper/Views/Customer/_DetailsPartialView.cshtml
@model CustomTagHelper.Models.CustomerViewModel

<dl class="row">
    <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Id)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Id)
    </dd>
    <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Firstname)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Firstname)
    </dd>
    <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Lastname)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Lastname)
    </dd>
    <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Username)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Username)
    </dd>
    <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.BirthDate)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.BirthDate)
    </dd>
    <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Email)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Email)
    </dd>
</dl>

CustomTagHelper/CustomTagHelper/Views/Customer/_EditPartialView.cshtml
@model CustomTagHelper.Models.CustomerViewModel

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Id" class="control-label"></label>
        <input asp-for="Id" class="form-control" />
        <span asp-validation-for="Id" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Firstname" class="control-label"></label>
        <input asp-for="Firstname" class="form-control" />
        <span asp-validation-for="Firstname" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Lastname" class="control-label"></label>
        <input asp-for="Lastname" class="form-control" />
        <span asp-validation-for="Lastname" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Username" class="control-label"></label>
        <input asp-for="Username" class="form-control" />
        <span asp-validation-for="Username" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="BirthDate" class="control-label"></label>
        <input asp-for="BirthDate" class="form-control" />
        <span asp-validation-for="BirthDate" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email" class="control-label"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
    </div>
</form>

CustomTagHelper/CustomTagHelper/Views/Customer/_IndexPartialView.cshtml
@model IEnumerable<CustomTagHelper.Models.CustomerViewModel>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Firstname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lastname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BirthDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Firstname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lastname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Username)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

CustomTagHelper/CustomTagHelper/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CustomTagHelper/CustomTagHelper/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CustomTagHelper</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CustomTagHelper.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CustomTagHelper</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CustomTagHelper - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/taghelpers/ajax-button-tag-helper.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>